name: Check for broken links

on:
  workflow_dispatch:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@1d97d84f0bc547f7b25f4c2170d87d810dc2fb2c # v2.4.0
        with:
          args: --verbose --no-progress './**/*.md' './**/*.html' './**/*.erb' --accept 403,200,429
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          
