name: Check for broken links

on:
  workflow_dispatch:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  check_links:
    runs-on: ubuntu-latest
    container:
      image: ministryofjustice/tech-docs-github-pages-publisher:2
    steps:
    - uses: actions/checkout@v4
    - name: htmlproofer
      run: /publishing-scripts/publish.sh no-repository-changes
