name: Check for broken links

on:
  workflow_dispatch:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@f81112d0d2814ded911bd23e3beaa9dda9093915 # v2.1.0
        with:
          args: --verbose --no-progress './**/*.md' './**/*.html' './**/*.erb' --accept 403,200,429
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          
