name: Doc expiry checker

on:
  workflow_dispatch:
  schedule:
    - cron: '30 09 * * 2' # At 09:30 on Tuesday (GMT)

jobs:
  doc-expiry-py:
    runs-on: ubuntu-latest
    steps:
      - name: Python3 Setup
        uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5.4.0
        with:
          python-version: 3.10.10
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install dependencies
        run: |
          pip install -r scripts/requirements.txt
      
      - name: Run scrape script
        env:
          TEAMS_WEBHOOK_URL: ${{ secrets.ALZ_NOTIFICATION_WEBHOOK }}
        run : |
          python scripts/expiry-scrape.py
