name: Doc expiry checker

on:
  workflow_dispatch:
  schedule:
    - cron: '0 10 * * 1' # At 10:00 on Monday

jobs:
  doc-expiry-py:
    runs-on: ubuntu-latest
    steps:
      - name: Python3 Setup
        uses: actions/setup-python@v4
        with:
          python-version: 3.10
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          pip install -r scripts/requirements.txt
      
      - name: Run scrape script
        env:
          TEAMS_WEBHOOK_URL: ${{ secrets.ALZ_NOTIFICATION_WEBHOOK }}
        run : |
          python scripts/expiry-scrape.py


